package ru.larten.autotest.addressbook;// Generated by Selenium IDE
import org.junit.Test;

public class CreateGroupTest extends TestBase {

  @Test
  public void testGroupCreation() {
    goToPageGroups();
    createNewGroup(new GroupData("test_group", "test_group_header", "test_group_footer"));
    goToPageGroups();
  }

}
