package ru.larten.autotest.addressbook;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class CreateContactTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost/addressbook/");
    driver.manage().window().setSize(new Dimension(974, 1040));
    login("admin", "secret");
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void createContactTest() {
    goToPageCreateContact();
    createContact(new ContactData("user1", "userovich1", "lastname1", "larten", "1", "myCompany", "Russia, Samara, Gastello st. 43A", "d.smolenskii@tezis-doc.ru"));
  }

  private void createContact(ContactData contactData) {
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys(contactData.getFirstname());
    driver.findElement(By.name("middlename")).sendKeys(contactData.getMiddlename());
    driver.findElement(By.name("lastname")).sendKeys(contactData.getLastname());
    driver.findElement(By.name("nickname")).sendKeys(contactData.getNickname());
    driver.findElement(By.name("photo")).sendKeys(Keys.ENTER);
    driver.findElement(By.name("title")).sendKeys(contactData.getTitle());
    driver.findElement(By.name("company")).sendKeys(contactData.getCompanyName());
    driver.findElement(By.name("address")).sendKeys(contactData.getAddress());
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys(contactData.getEmail());
    driver.findElement(By.cssSelector("input:nth-child(87)")).click();
  }

  private void goToPageCreateContact() {
    driver.findElement(By.linkText("add new")).click();
  }

  private void login(String username, String password) {
    driver.findElement(By.name("user")).sendKeys(username);
    driver.findElement(By.name("pass")).sendKeys(password);
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
  }
}
